/*
 * Debug Levels:
 * 1: normal
 * 2: verbose
 * 3: really verbose
 */
#define DEBUG 1

#define BATTERY_POWERED true

#define CONTROL_PANEL_BUTTON_PIN 5
#define CONTROL_PANEL_READY_LED_PIN 21
#define CONTROL_PANEL_RUNNING_LED_PIN 22
#define CONTROL_PANEL_ERROR_LED_PIN 26
#define CONTROL_PANEL_BATTERY_LED_PIN 27

#define HCSR04_RIGHT_TRIGGER_PIN 8
#define HCSR04_RIGHT_ECHO_PIN 9
#define HCSR04_BACK_TRIGGER_PIN 18
#define HCSR04_BACK_ECHO_PIN 19
#define HCSR04_LEFT_TRIGGER_PIN 2
#define HCSR04_LEFT_ECHO_PIN 3